---
title: "Rethinking how students learn to design programs"
author: "Author Blinded for Review"
date: "March 20, 2016"
abstract: |
  This paper focuses on a historically understudied area in computing education: attending to students’ *design thinking* in university-level introductory programming courses. We offer an account of one student---"Rebecca"---and her experiences and code from a second-semester course on programming concepts for engineers. Using data from both code snapshots and clinical interviews, we explicate both the challenges of studying students’ software design processes and the potential for such study to inform accounts of teaching and learning.We detail the case of Rebecca, a first-year Electrical Engineering student taking a required 2^nd^-semester programming course in C. Our analysis focuses on two related aspects of Rebecca’s code for a multi-week project:

  1. The origin, nature, and evolution of unusual structural and behavioral features of Rebecca’s code
  2. The subtle, yet complex reasons that led Rebecca to make particular design choices in her code

  Our data comes from ethnographic observation of Rebecca’s class, fine-grained compile-time snapshots of Rebecca’s codebase, and semistructured interviews with Rebecca. We first present an analysis of the compile-time snapshots, detailing Rebecca’s unusual use of file-scanning loops and her seven-fold repetition of a particular code chunk (once for each day of the week). We then augment that analysis with data from semi-structured interviews with Rebecca, which reveal that affect [@hannula_affect_2004; @eynde_case_2006] and framing [@vandesande_achieving_2012; @hammer_resources_2005] offer substantial explanatory power for understanding why Rebecca made particular design choices.

# Citation options
bibliography: bibliography.bib
biblio-style: numbers
---

# Introduction

## We need more research on how software gets designed

In 2010, the journal *Design Studies* devoted a special issue to studies of how professional software engineers design complex systems [@petre_editorial_2010]. The journal issue featured five different research perspectives on the same dataset: videos of three professional software engineering teams trying to design a traffic simulator. The existence of the journal issue, the monograph that followed it [@petre_software_2014] and the investigations contained therein, were motivated by what the issue’s editors saw as a pressing need:

> *[N]ot enough is known about the formative stages of software design.* The software engineering community has produced numerous design tools and languages, but, in practice, when software designers are first presented with a novel design problem, they more often than not will eschew these tools and languages. During formative design, software engineers spend a great deal of time engaging in creative, exploratory design thinking using pen and paper or a whiteboard---whether alone or in a small group. However, not enough is known about how software designers work in such settings. What do designers actually do during early software design? How do they communicate? What sorts of drawings do they create? *What kinds of strategies do they [software engineers] apply in exploring the vast space of possible designs?* [@petre_editorial_2010 p. 533; emphasis mine]

Research in both the special issue [@petre_editorial_2010] and the monograph [@petre_software_2014] takes on a variety of challenges in the study of expert software design practice. One challenge, for example, is that of understanding how engineers process, prioritize, and cope with design requirements. Ball, Linden, Onarheim, and Christensen [-@ball_design_2010] observed that engineers deploy mixed strategies, developing solutions breadth-first for easy problems and depth-first for more complex problems. They also found that the more complex a requirement became, the more likely engineers were to create speculative simulations (through talk and representations) about how a system might work to solve that problem [@ball_design_2010].

Looking at the design sessions longitudinally, Baker and van der Hoek [-@baker_ideas_2010] explored the shape and trajectory of how ideas generated in the design process develop and relate to one another. Those researchers found roughly a third of the ideas discussed in a typical design session “were reiterations or rephrasings of previously stated ideas” [@baker_ideas_2010 p. 604]. While it is perhaps frustrating that ideas would be repeated so much, the authors argue such repetition can be viewed as a kind of continual revisitation to make sure a proposed design coheres:

> Rather than representing a failure on the part of the designers, this repetition seems to be a necessary character of successful design sessions. Each time an idea is resurrected it is placed them [sic] in a new context, and compared to different aspects of the system. In this way, a concept of compatible, elegant design ideas is slowly converged upon. [@baker_ideas_2010 p. 607]

Perhaps most germane to the work presented here, Jackson [-@jackson_representing_2010] explores the role of *structure* in software design. Jackson’s meaning in using the word “structure” is broad. It can best be described as the arrangement of and relationships between the elements of a system. But, the broadness is deliberate, because Jackson’s overall argument is that the work of software often involves a coordination of different structures, some of which drive the organization of others. In Jackson’s [-@jackson_representing_2010] analysis of the dataset, designers worked with various kinds of structured sets to build software that could simulate traffic patterns in a city section. I argue, then, that part of the work of software design becomes that of defining and coordinating structural relationships at various levels of abstraction:

- *The data-to-be-modeled*. In this case, the analog was a system of roads and intersections on which one can simulate traffic. Schematically, this system can be structured on the Cartesian plane of a map. Its representation (a diagrammatic map-like network of streets) works to organize how the system-to-be-modeled looks in the real world.
- The *actors* present in the system-to-be-modeled. In this case, that means abstracting from the map to all of the *actors* that simulator software would need to send data to and get data from: including traffic signal units, traffic signal controllers, drivers, and vehicle sensors.
- The *meta-entities* that must exist to execute the actual simulation. Crucially, these abstractions may not be the same as the actors *in* the system.[^1] In this case, additional computational entities must be added to carry out a traffic simulation, such as an arrivals model and a simulation clock [@jackson_representing_2010 p. 559]
- The *programming code* that embodies the data and behaviors of the entities and meta-entities. While to some degree aesthetic, the symbolic structure of code is in many ways driven by decisions about structural relationships in other levels of abstraction.

How engineers develop and interact with even the first three kinds of structural representations can profoundly influence the nature and quality of the code they produce. As Jackson [-@jackson_representing_2010] observes---in notable contrast to [@baker_ideas_2010]---early negotiations of structure led to design decisions that were *not* revisited later:

> The traffic simulation problem was of a kind unfamiliar to all three design teams. All three quite rightly tried immediately to assimilate the problem to something they already knew. Two teams took the view that the problem was an instance of the Model-View-Controller (MVC) software pattern; the third identified the problem as ‘like a drawing program’. Unfortunately, these hasty classifications were inadequate; but in every case they were accepted uncritically and never explicitly questioned. [@jackson_representing_2010 p. 564]

Ultimately, careful study of how software engineers design shows us the enormous complexity involved in producing effective and thorough code. And, much of that complexity is both afforded and constrained by talk, representational infrastructure, and knowledge of larger-scale solution patterns. It’s striking, then, that this research perspective on how programing design work gets done---for example, the detailed ethnomethodological analysis by Rooksby, Ikeya and colleagues on how engineers use a whiteboard [@rooksby_just_2010; @rooksby_collaboration_2012; @ikeya_recovering_2012]---seems largely underrepresented in studies of how students learn to program. Instead, the latest generation of research on student learning in programming has focused much more extensively on questions like *how can we assess and mitigate students’ difficulty in programming?* than it has on questions like *how do students learn and display evidence of design thinking in programming?*

## Acknowledgments

Blinded for review.

\newpage{}
## References
